# Generated by Django 5.2.3 on 2025-06-26 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("sturecid", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("student_class", models.CharField(max_length=50)),
                ("section", models.CharField(blank=True, max_length=50, null=True)),
                ("claid", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excelhandler.institution",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "institution")},
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "test_code",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("test_date", models.DateField(blank=True, null=True)),
                ("test_type", models.CharField(max_length=50)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excelhandler.batch",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excelhandler.institution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentTestPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.FloatField()),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excelhandler.student",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excelhandler.test",
                    ),
                ),
            ],
            options={
                "ordering": ["test", "-total_score"],
                "unique_together": {("student", "test")},
            },
        ),
        migrations.CreateModel(
            name="StudentSubjectPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_tag", models.CharField(max_length=50)),
                ("subject_score", models.FloatField()),
                ("subject_rank", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excelhandler.student",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excelhandler.test",
                    ),
                ),
            ],
            options={
                "ordering": ["test", "subject_tag", "-subject_score"],
                "unique_together": {("student", "test", "subject_tag")},
            },
        ),
        migrations.CreateModel(
            name="StudentResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_number", models.PositiveIntegerField()),
                ("selected_option", models.PositiveIntegerField()),
                ("is_correct", models.BooleanField()),
                ("score_awarded", models.FloatField()),
                (
                    "sturecid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excelhandler.student",
                    ),
                ),
                (
                    "test_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excelhandler.test",
                    ),
                ),
            ],
            options={
                "unique_together": {("sturecid", "test_code", "question_number")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_number", models.PositiveIntegerField()),
                ("correct_option", models.PositiveIntegerField()),
                ("subject_tag", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "test_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excelhandler.test",
                    ),
                ),
            ],
            options={
                "unique_together": {("test_code", "question_number")},
            },
        ),
    ]
